# Generated by Django 5.2.8 on 2025-11-24 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_profiles(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    UserProfile = apps.get_model('ideas', 'UserProfile')
    for user in User.objects.all():
        role = 'admin' if user.is_staff else 'submitter'
        UserProfile.objects.get_or_create(user=user, defaults={'role': role})


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('submitter', 'Submitter'), ('reviewer', 'Reviewer'), ('admin', 'Administrator')], default='submitter', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.RunPython(create_initial_profiles, migrations.RunPython.noop),
    ]
